sudo: false
dist: bionic
language: python
python:
  - "2.7"
  - "3.7"
install:
    - pip install tox-travis
    - pip install coveralls
    - pip install -r requirements.txt
    - pip install -r tests/requirements.txt
script:
    - tox
    - pytest --cov=eevee
after_success: coveralls
